import { Address } from "./address";
import { Rating } from "./rating";
import { DeliveryEtaMinutes } from "./delivery-eta-minutes";
import { Deal } from "./deal";
import { Offer } from "./offer";
import { Logo } from "./logo";
import { CuisineType } from "./cuisine-type";
import { Cuisine } from "./cuisine";
import { ScoreMetaDaum } from "./score-meta-daum";


export interface Restaurants {
    Id: number;
    Name: string;
    UniqueName: string;
    Address: Address;
    City: string;
    Postcode: string;
    Latitude: number;
    Longitude: number;
    Rating: Rating;
    RatingStars: number;
    NumberOfRatings: number;
    RatingAverage: number;
    Description: string;
    Url: string;
    LogoUrl: string;
    IsTestRestaurant: boolean;
    IsHalal: boolean;
    IsNew: boolean;
    ReasonWhyTemporarilyOffline: string;
    DriveDistance: number;
    DriveInfoCalculated: boolean;
    IsCloseBy: boolean;
    OfferPercent: number;
    NewnessDate: string;
    OpeningTime: string;
    OpeningTimeUtc: any;
    OpeningTimeIso: string;
    OpeningTimeLocal: string;
    DeliveryOpeningTimeLocal: string;
    DeliveryOpeningTime: string;
    DeliveryOpeningTimeUtc: any;
    DeliveryStartTime: string;
    DeliveryTime: any;
    DeliveryTimeMinutes: any;
    DeliveryWorkingTimeMinutes: number;
    DeliveryEtaMinutes: DeliveryEtaMinutes;
    IsCollection: boolean;
    IsDelivery: boolean;
    IsFreeDelivery: boolean;
    IsOpenNowForCollection: boolean;
    IsOpenNowForDelivery: boolean;
    IsOpenNowForPreorder: boolean;
    IsOpenNow: boolean;
    IsTemporarilyOffline: boolean;
    DeliveryMenuId: any;
    CollectionMenuId: any;
    DeliveryZipcode: any;
    DeliveryCost: number;
    MinimumDeliveryValue: number;
    SecondDateRanking: number;
    DefaultDisplayRank: number;
    SponsoredPosition: number;
    SecondDateRank: number;
    Score: number;
    IsTemporaryBoost: boolean;
    IsSponsored: boolean;
    IsPremier: boolean;
    HygieneRating: any;
    ShowSmiley: boolean;
    SmileyDate: any;
    SmileyElite: boolean;
    SmileyResult: any;
    SmileyUrl: any;
    SendsOnItsWayNotifications: boolean;
    BrandName: string;
    IsBrand: boolean;
    LastUpdated: string;
    Deals: Deal[];
    Offers: Offer[];
    Logo: Logo[];
    Tags: string[];
    DeliveryChargeBands: any[];
    CuisineTypes: CuisineType[];
    Cuisines: Cuisine[];
    ScoreMetaData: ScoreMetaDaum[];
    Badges: any[];
    OpeningTimes: any[];
    ServiceableAreas: any[];
}

